package hackathon.com.sansad.models.chat;

import com.google.gson.annotations.Expose;

/**
 * Created by utk994 on 10/2/2015.
 */
public class Messages {
    @Expose
    private String id;
    @Expose
    private String sender;
    @Expose
    private String reciever;
    @Expose
    private String message;
    @Expose
    private String status;
    @Expose
    private String timestamp;
    @Expose
    private String autogenerated;


    /**
     * @return The id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id The id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return The name
     */
    public String getSender() {
        return sender;
    }

    /**
     * @param sender The name
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * @return The username
     */
    public String getReciever() {
        return reciever;
    }

    /**
     * @param reciever The type
     */
    public void setReciever(String reciever) {
        this.reciever = reciever;
    }

    /**
     * @return The minimum spending
     */
    public String getMessage() {
        return message;
    }

    /**
     * @param message The Minimum Spending
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * @return The rating
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status The rating
     */
    public void setStatus(String status) {
        this.status = status;
    }


    /**
     * @return The address
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * @param timestamp The address
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * @return The address
     */
    public String getAutogenerated() {
        return autogenerated;
    }

    /**
     * @param autogenerated The address
     */
    public void setAutogenerated(String autogenerated) {
        this.autogenerated = autogenerated;
    }

    @Override
    public String toString() {
        return "id " + this.id + ", Sender:"
                + this.sender+ ", Reciever: " + this.reciever
                + "message" + this.message + "Autogen" + this.autogenerated
                + "timestamp:" + this.timestamp ;
    }
}


